set NoQuitOnFinish 1
set TOP_LEVEL /tb_top

set I_MEMORY [concat [find signals sim:$TOP_LEVEL/ram/instr*_i] [find signals sim:$TOP_LEVEL/ram/instr*_o]]
set D_MEMORY [concat [find signals sim:$TOP_LEVEL/ram/data*_i] [find signals sim:$TOP_LEVEL/ram/data*_o]]
set IF       [concat [find signals sim:$TOP_LEVEL/dut/u_ibex_core/if_stage_i/*_i] [find signals sim:$TOP_LEVEL/dut/u_ibex_core/if_stage_i/*_o]]
set IF_CDEC  [concat [find signals sim:$TOP_LEVEL/dut/u_ibex_core/if_stage_i/compressed_decoder_i/*_i] [find signals sim:$TOP_LEVEL/dut/u_ibex_core/if_stage_i/compressed_decoder_i/*_o]]
set IF_PREF  [concat [find signals sim:$TOP_LEVEL/dut/u_ibex_core/if_stage_i/gen_prefetch_buffer/*_i] [find signals sim:$TOP_LEVEL/dut/u_ibex_core/if_stage_i/gen_prefetch_buffer/*_o]]
set ID       [concat [find signals sim:$TOP_LEVEL/dut/u_ibex_core/id_stage_i/*_i] [find signals sim:$TOP_LEVEL/dut/u_ibex_core/id_stage_i/*_o]]
set ID_DEC   [concat [find signals sim:$TOP_LEVEL/dut/u_ibex_core/id_stage_i/decoder_i/*_i] [find signals sim:$TOP_LEVEL/dut/u_ibex_core/id_stage_i/decoder_i/*_o]]
set ID_CONTR [concat [find signals sim:$TOP_LEVEL/dut/u_ibex_core/id_stage_i/controller_i/*_i] [find signals sim:$TOP_LEVEL/dut/u_ibex_core/id_stage_i/controller_i/*_o]]
set ID_STALL [concat [find signals sim:$TOP_LEVEL/dut/u_ibex_core/id_stage_i/gen_stall_mem/*_i] [find signals sim:$TOP_LEVEL/dut/u_ibex_core/id_stage_i/gen_stall_mem/*_o]]
set EX       [concat [find signals sim:$TOP_LEVEL/dut/u_ibex_core/ex_block_i/*_i] [find signals sim:$TOP_LEVEL/dut/u_ibex_core/ex_block_i/*_o]]
set EX_ALU   [concat [find signals sim:$TOP_LEVEL/dut/u_ibex_core/ex_block_i/alu_i/*_i] [find signals sim:$TOP_LEVEL/dut/u_ibex_core/ex_block_i/alu_i/*_o]]
set LSU      [concat [find signals sim:$TOP_LEVEL/dut/u_ibex_core/load_store_unit_i/*_i] [find signals sim:$TOP_LEVEL/dut/u_ibex_core/load_store_unit_i/*_o]]
set WB       [concat [find signals sim:$TOP_LEVEL/dut/u_ibex_core/wb_stage_i/*_i] [find signals sim:$TOP_LEVEL/dut/u_ibex_core/wb_stage_i/*_o]]

###################### PIPELINE CONTROL #######################

add wave -group PIPELINE\ CONTROL -label CLOCK   -color green $TOP_LEVEL/clk
add wave -group PIPELINE\ CONTROL -label RESET_N -color green $TOP_LEVEL/reset_n
add wave -group PIPELINE\ CONTROL -label EXIT_OK -color green $TOP_LEVEL/exit_success
add wave -group PIPELINE\ CONTROL -label IF_PC   -color green $TOP_LEVEL/dut/u_ibex_core/if_stage_i/pc_if_o
add wave -group PIPELINE\ CONTROL -label ID_PC   -color green $TOP_LEVEL/dut/u_ibex_core/if_stage_i/pc_id_o

###################### REGISTER FILE #######################

quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_1__rf_reg_q_reg_31_/Q, g_rf_flops_1__rf_reg_q_reg_30_/Q, g_rf_flops_1__rf_reg_q_reg_29_/Q, g_rf_flops_1__rf_reg_q_reg_28_/Q, g_rf_flops_1__rf_reg_q_reg_27_/Q, g_rf_flops_1__rf_reg_q_reg_26_/Q, g_rf_flops_1__rf_reg_q_reg_25_/Q, g_rf_flops_1__rf_reg_q_reg_24_/Q, g_rf_flops_1__rf_reg_q_reg_23_/Q, g_rf_flops_1__rf_reg_q_reg_22_/Q, g_rf_flops_1__rf_reg_q_reg_21_/Q, g_rf_flops_1__rf_reg_q_reg_20_/Q, g_rf_flops_1__rf_reg_q_reg_19_/Q, g_rf_flops_1__rf_reg_q_reg_18_/Q, g_rf_flops_1__rf_reg_q_reg_17_/Q, g_rf_flops_1__rf_reg_q_reg_16_/Q, g_rf_flops_1__rf_reg_q_reg_15_/Q, g_rf_flops_1__rf_reg_q_reg_14_/Q, g_rf_flops_1__rf_reg_q_reg_13_/Q, g_rf_flops_1__rf_reg_q_reg_12_/Q, g_rf_flops_1__rf_reg_q_reg_11_/Q, g_rf_flops_1__rf_reg_q_reg_10_/Q, g_rf_flops_1__rf_reg_q_reg_9_/Q, g_rf_flops_1__rf_reg_q_reg_8_/Q, g_rf_flops_1__rf_reg_q_reg_7_/Q, g_rf_flops_1__rf_reg_q_reg_6_/Q, g_rf_flops_1__rf_reg_q_reg_5_/Q, g_rf_flops_1__rf_reg_q_reg_4_/Q, g_rf_flops_1__rf_reg_q_reg_3_/Q, g_rf_flops_1__rf_reg_q_reg_2_/Q, g_rf_flops_1__rf_reg_q_reg_1_/Q, g_rf_flops_1__rf_reg_q_reg_0_/Q}} reg1
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_2__rf_reg_q_reg_31_/Q, g_rf_flops_2__rf_reg_q_reg_30_/Q, g_rf_flops_2__rf_reg_q_reg_29_/Q, g_rf_flops_2__rf_reg_q_reg_28_/Q, g_rf_flops_2__rf_reg_q_reg_27_/Q, g_rf_flops_2__rf_reg_q_reg_26_/Q, g_rf_flops_2__rf_reg_q_reg_25_/Q, g_rf_flops_2__rf_reg_q_reg_24_/Q, g_rf_flops_2__rf_reg_q_reg_23_/Q, g_rf_flops_2__rf_reg_q_reg_22_/Q, g_rf_flops_2__rf_reg_q_reg_21_/Q, g_rf_flops_2__rf_reg_q_reg_20_/Q, g_rf_flops_2__rf_reg_q_reg_19_/Q, g_rf_flops_2__rf_reg_q_reg_18_/Q, g_rf_flops_2__rf_reg_q_reg_17_/Q, g_rf_flops_2__rf_reg_q_reg_16_/Q, g_rf_flops_2__rf_reg_q_reg_15_/Q, g_rf_flops_2__rf_reg_q_reg_14_/Q, g_rf_flops_2__rf_reg_q_reg_13_/Q, g_rf_flops_2__rf_reg_q_reg_12_/Q, g_rf_flops_2__rf_reg_q_reg_11_/Q, g_rf_flops_2__rf_reg_q_reg_10_/Q, g_rf_flops_2__rf_reg_q_reg_9_/Q, g_rf_flops_2__rf_reg_q_reg_8_/Q, g_rf_flops_2__rf_reg_q_reg_7_/Q, g_rf_flops_2__rf_reg_q_reg_6_/Q, g_rf_flops_2__rf_reg_q_reg_5_/Q, g_rf_flops_2__rf_reg_q_reg_4_/Q, g_rf_flops_2__rf_reg_q_reg_3_/Q, g_rf_flops_2__rf_reg_q_reg_2_/Q, g_rf_flops_2__rf_reg_q_reg_1_/Q, g_rf_flops_2__rf_reg_q_reg_0_/Q}} reg2
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_3__rf_reg_q_reg_31_/Q, g_rf_flops_3__rf_reg_q_reg_30_/Q, g_rf_flops_3__rf_reg_q_reg_29_/Q, g_rf_flops_3__rf_reg_q_reg_28_/Q, g_rf_flops_3__rf_reg_q_reg_27_/Q, g_rf_flops_3__rf_reg_q_reg_26_/Q, g_rf_flops_3__rf_reg_q_reg_25_/Q, g_rf_flops_3__rf_reg_q_reg_24_/Q, g_rf_flops_3__rf_reg_q_reg_23_/Q, g_rf_flops_3__rf_reg_q_reg_22_/Q, g_rf_flops_3__rf_reg_q_reg_21_/Q, g_rf_flops_3__rf_reg_q_reg_20_/Q, g_rf_flops_3__rf_reg_q_reg_19_/Q, g_rf_flops_3__rf_reg_q_reg_18_/Q, g_rf_flops_3__rf_reg_q_reg_17_/Q, g_rf_flops_3__rf_reg_q_reg_16_/Q, g_rf_flops_3__rf_reg_q_reg_15_/Q, g_rf_flops_3__rf_reg_q_reg_14_/Q, g_rf_flops_3__rf_reg_q_reg_13_/Q, g_rf_flops_3__rf_reg_q_reg_12_/Q, g_rf_flops_3__rf_reg_q_reg_11_/Q, g_rf_flops_3__rf_reg_q_reg_10_/Q, g_rf_flops_3__rf_reg_q_reg_9_/Q, g_rf_flops_3__rf_reg_q_reg_8_/Q, g_rf_flops_3__rf_reg_q_reg_7_/Q, g_rf_flops_3__rf_reg_q_reg_6_/Q, g_rf_flops_3__rf_reg_q_reg_5_/Q, g_rf_flops_3__rf_reg_q_reg_4_/Q, g_rf_flops_3__rf_reg_q_reg_3_/Q, g_rf_flops_3__rf_reg_q_reg_2_/Q, g_rf_flops_3__rf_reg_q_reg_1_/Q, g_rf_flops_3__rf_reg_q_reg_0_/Q}} reg3 
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_4__rf_reg_q_reg_31_/Q, g_rf_flops_4__rf_reg_q_reg_30_/Q, g_rf_flops_4__rf_reg_q_reg_29_/Q, g_rf_flops_4__rf_reg_q_reg_28_/Q, g_rf_flops_4__rf_reg_q_reg_27_/Q, g_rf_flops_4__rf_reg_q_reg_26_/Q, g_rf_flops_4__rf_reg_q_reg_25_/Q, g_rf_flops_4__rf_reg_q_reg_24_/Q, g_rf_flops_4__rf_reg_q_reg_23_/Q, g_rf_flops_4__rf_reg_q_reg_22_/Q, g_rf_flops_4__rf_reg_q_reg_21_/Q, g_rf_flops_4__rf_reg_q_reg_20_/Q, g_rf_flops_4__rf_reg_q_reg_19_/Q, g_rf_flops_4__rf_reg_q_reg_18_/Q, g_rf_flops_4__rf_reg_q_reg_17_/Q, g_rf_flops_4__rf_reg_q_reg_16_/Q, g_rf_flops_4__rf_reg_q_reg_15_/Q, g_rf_flops_4__rf_reg_q_reg_14_/Q, g_rf_flops_4__rf_reg_q_reg_13_/Q, g_rf_flops_4__rf_reg_q_reg_12_/Q, g_rf_flops_4__rf_reg_q_reg_11_/Q, g_rf_flops_4__rf_reg_q_reg_10_/Q, g_rf_flops_4__rf_reg_q_reg_9_/Q, g_rf_flops_4__rf_reg_q_reg_8_/Q, g_rf_flops_4__rf_reg_q_reg_7_/Q, g_rf_flops_4__rf_reg_q_reg_6_/Q, g_rf_flops_4__rf_reg_q_reg_5_/Q, g_rf_flops_4__rf_reg_q_reg_4_/Q, g_rf_flops_4__rf_reg_q_reg_3_/Q, g_rf_flops_4__rf_reg_q_reg_2_/Q, g_rf_flops_4__rf_reg_q_reg_1_/Q, g_rf_flops_4__rf_reg_q_reg_0_/Q}} reg4 
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_5__rf_reg_q_reg_31_/Q, g_rf_flops_5__rf_reg_q_reg_30_/Q, g_rf_flops_5__rf_reg_q_reg_29_/Q, g_rf_flops_5__rf_reg_q_reg_28_/Q, g_rf_flops_5__rf_reg_q_reg_27_/Q, g_rf_flops_5__rf_reg_q_reg_26_/Q, g_rf_flops_5__rf_reg_q_reg_25_/Q, g_rf_flops_5__rf_reg_q_reg_24_/Q, g_rf_flops_5__rf_reg_q_reg_23_/Q, g_rf_flops_5__rf_reg_q_reg_22_/Q, g_rf_flops_5__rf_reg_q_reg_21_/Q, g_rf_flops_5__rf_reg_q_reg_20_/Q, g_rf_flops_5__rf_reg_q_reg_19_/Q, g_rf_flops_5__rf_reg_q_reg_18_/Q, g_rf_flops_5__rf_reg_q_reg_17_/Q, g_rf_flops_5__rf_reg_q_reg_16_/Q, g_rf_flops_5__rf_reg_q_reg_15_/Q, g_rf_flops_5__rf_reg_q_reg_14_/Q, g_rf_flops_5__rf_reg_q_reg_13_/Q, g_rf_flops_5__rf_reg_q_reg_12_/Q, g_rf_flops_5__rf_reg_q_reg_11_/Q, g_rf_flops_5__rf_reg_q_reg_10_/Q, g_rf_flops_5__rf_reg_q_reg_9_/Q, g_rf_flops_5__rf_reg_q_reg_8_/Q, g_rf_flops_5__rf_reg_q_reg_7_/Q, g_rf_flops_5__rf_reg_q_reg_6_/Q, g_rf_flops_5__rf_reg_q_reg_5_/Q, g_rf_flops_5__rf_reg_q_reg_4_/Q, g_rf_flops_5__rf_reg_q_reg_3_/Q, g_rf_flops_5__rf_reg_q_reg_2_/Q, g_rf_flops_5__rf_reg_q_reg_1_/Q, g_rf_flops_5__rf_reg_q_reg_0_/Q}} reg5 
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_6__rf_reg_q_reg_31_/Q, g_rf_flops_6__rf_reg_q_reg_30_/Q, g_rf_flops_6__rf_reg_q_reg_29_/Q, g_rf_flops_6__rf_reg_q_reg_28_/Q, g_rf_flops_6__rf_reg_q_reg_27_/Q, g_rf_flops_6__rf_reg_q_reg_26_/Q, g_rf_flops_6__rf_reg_q_reg_25_/Q, g_rf_flops_6__rf_reg_q_reg_24_/Q, g_rf_flops_6__rf_reg_q_reg_23_/Q, g_rf_flops_6__rf_reg_q_reg_22_/Q, g_rf_flops_6__rf_reg_q_reg_21_/Q, g_rf_flops_6__rf_reg_q_reg_20_/Q, g_rf_flops_6__rf_reg_q_reg_19_/Q, g_rf_flops_6__rf_reg_q_reg_18_/Q, g_rf_flops_6__rf_reg_q_reg_17_/Q, g_rf_flops_6__rf_reg_q_reg_16_/Q, g_rf_flops_6__rf_reg_q_reg_15_/Q, g_rf_flops_6__rf_reg_q_reg_14_/Q, g_rf_flops_6__rf_reg_q_reg_13_/Q, g_rf_flops_6__rf_reg_q_reg_12_/Q, g_rf_flops_6__rf_reg_q_reg_11_/Q, g_rf_flops_6__rf_reg_q_reg_10_/Q, g_rf_flops_6__rf_reg_q_reg_9_/Q, g_rf_flops_6__rf_reg_q_reg_8_/Q, g_rf_flops_6__rf_reg_q_reg_7_/Q, g_rf_flops_6__rf_reg_q_reg_6_/Q, g_rf_flops_6__rf_reg_q_reg_5_/Q, g_rf_flops_6__rf_reg_q_reg_4_/Q, g_rf_flops_6__rf_reg_q_reg_3_/Q, g_rf_flops_6__rf_reg_q_reg_2_/Q, g_rf_flops_6__rf_reg_q_reg_1_/Q, g_rf_flops_6__rf_reg_q_reg_0_/Q}} reg6 
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_7__rf_reg_q_reg_31_/Q, g_rf_flops_7__rf_reg_q_reg_30_/Q, g_rf_flops_7__rf_reg_q_reg_29_/Q, g_rf_flops_7__rf_reg_q_reg_28_/Q, g_rf_flops_7__rf_reg_q_reg_27_/Q, g_rf_flops_7__rf_reg_q_reg_26_/Q, g_rf_flops_7__rf_reg_q_reg_25_/Q, g_rf_flops_7__rf_reg_q_reg_24_/Q, g_rf_flops_7__rf_reg_q_reg_23_/Q, g_rf_flops_7__rf_reg_q_reg_22_/Q, g_rf_flops_7__rf_reg_q_reg_21_/Q, g_rf_flops_7__rf_reg_q_reg_20_/Q, g_rf_flops_7__rf_reg_q_reg_19_/Q, g_rf_flops_7__rf_reg_q_reg_18_/Q, g_rf_flops_7__rf_reg_q_reg_17_/Q, g_rf_flops_7__rf_reg_q_reg_16_/Q, g_rf_flops_7__rf_reg_q_reg_15_/Q, g_rf_flops_7__rf_reg_q_reg_14_/Q, g_rf_flops_7__rf_reg_q_reg_13_/Q, g_rf_flops_7__rf_reg_q_reg_12_/Q, g_rf_flops_7__rf_reg_q_reg_11_/Q, g_rf_flops_7__rf_reg_q_reg_10_/Q, g_rf_flops_7__rf_reg_q_reg_9_/Q, g_rf_flops_7__rf_reg_q_reg_8_/Q, g_rf_flops_7__rf_reg_q_reg_7_/Q, g_rf_flops_7__rf_reg_q_reg_6_/Q, g_rf_flops_7__rf_reg_q_reg_5_/Q, g_rf_flops_7__rf_reg_q_reg_4_/Q, g_rf_flops_7__rf_reg_q_reg_3_/Q, g_rf_flops_7__rf_reg_q_reg_2_/Q, g_rf_flops_7__rf_reg_q_reg_1_/Q, g_rf_flops_7__rf_reg_q_reg_0_/Q}} reg7 
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_8__rf_reg_q_reg_31_/Q, g_rf_flops_8__rf_reg_q_reg_30_/Q, g_rf_flops_8__rf_reg_q_reg_29_/Q, g_rf_flops_8__rf_reg_q_reg_28_/Q, g_rf_flops_8__rf_reg_q_reg_27_/Q, g_rf_flops_8__rf_reg_q_reg_26_/Q, g_rf_flops_8__rf_reg_q_reg_25_/Q, g_rf_flops_8__rf_reg_q_reg_24_/Q, g_rf_flops_8__rf_reg_q_reg_23_/Q, g_rf_flops_8__rf_reg_q_reg_22_/Q, g_rf_flops_8__rf_reg_q_reg_21_/Q, g_rf_flops_8__rf_reg_q_reg_20_/Q, g_rf_flops_8__rf_reg_q_reg_19_/Q, g_rf_flops_8__rf_reg_q_reg_18_/Q, g_rf_flops_8__rf_reg_q_reg_17_/Q, g_rf_flops_8__rf_reg_q_reg_16_/Q, g_rf_flops_8__rf_reg_q_reg_15_/Q, g_rf_flops_8__rf_reg_q_reg_14_/Q, g_rf_flops_8__rf_reg_q_reg_13_/Q, g_rf_flops_8__rf_reg_q_reg_12_/Q, g_rf_flops_8__rf_reg_q_reg_11_/Q, g_rf_flops_8__rf_reg_q_reg_10_/Q, g_rf_flops_8__rf_reg_q_reg_9_/Q, g_rf_flops_8__rf_reg_q_reg_8_/Q, g_rf_flops_8__rf_reg_q_reg_7_/Q, g_rf_flops_8__rf_reg_q_reg_6_/Q, g_rf_flops_8__rf_reg_q_reg_5_/Q, g_rf_flops_8__rf_reg_q_reg_4_/Q, g_rf_flops_8__rf_reg_q_reg_3_/Q, g_rf_flops_8__rf_reg_q_reg_2_/Q, g_rf_flops_8__rf_reg_q_reg_1_/Q, g_rf_flops_8__rf_reg_q_reg_0_/Q}} reg8 
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_9__rf_reg_q_reg_31_/Q, g_rf_flops_9__rf_reg_q_reg_30_/Q, g_rf_flops_9__rf_reg_q_reg_29_/Q, g_rf_flops_9__rf_reg_q_reg_28_/Q, g_rf_flops_9__rf_reg_q_reg_27_/Q, g_rf_flops_9__rf_reg_q_reg_26_/Q, g_rf_flops_9__rf_reg_q_reg_25_/Q, g_rf_flops_9__rf_reg_q_reg_24_/Q, g_rf_flops_9__rf_reg_q_reg_23_/Q, g_rf_flops_9__rf_reg_q_reg_22_/Q, g_rf_flops_9__rf_reg_q_reg_21_/Q, g_rf_flops_9__rf_reg_q_reg_20_/Q, g_rf_flops_9__rf_reg_q_reg_19_/Q, g_rf_flops_9__rf_reg_q_reg_18_/Q, g_rf_flops_9__rf_reg_q_reg_17_/Q, g_rf_flops_9__rf_reg_q_reg_16_/Q, g_rf_flops_9__rf_reg_q_reg_15_/Q, g_rf_flops_9__rf_reg_q_reg_14_/Q, g_rf_flops_9__rf_reg_q_reg_13_/Q, g_rf_flops_9__rf_reg_q_reg_12_/Q, g_rf_flops_9__rf_reg_q_reg_11_/Q, g_rf_flops_9__rf_reg_q_reg_10_/Q, g_rf_flops_9__rf_reg_q_reg_9_/Q, g_rf_flops_9__rf_reg_q_reg_8_/Q, g_rf_flops_9__rf_reg_q_reg_7_/Q, g_rf_flops_9__rf_reg_q_reg_6_/Q, g_rf_flops_9__rf_reg_q_reg_5_/Q, g_rf_flops_9__rf_reg_q_reg_4_/Q, g_rf_flops_9__rf_reg_q_reg_3_/Q, g_rf_flops_9__rf_reg_q_reg_2_/Q, g_rf_flops_9__rf_reg_q_reg_1_/Q, g_rf_flops_9__rf_reg_q_reg_0_/Q}} reg9 
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_10__rf_reg_q_reg_31_/Q, g_rf_flops_10__rf_reg_q_reg_30_/Q, g_rf_flops_10__rf_reg_q_reg_29_/Q, g_rf_flops_10__rf_reg_q_reg_28_/Q, g_rf_flops_10__rf_reg_q_reg_27_/Q, g_rf_flops_10__rf_reg_q_reg_26_/Q, g_rf_flops_10__rf_reg_q_reg_25_/Q, g_rf_flops_10__rf_reg_q_reg_24_/Q, g_rf_flops_10__rf_reg_q_reg_23_/Q, g_rf_flops_10__rf_reg_q_reg_22_/Q, g_rf_flops_10__rf_reg_q_reg_21_/Q, g_rf_flops_10__rf_reg_q_reg_20_/Q, g_rf_flops_10__rf_reg_q_reg_19_/Q, g_rf_flops_10__rf_reg_q_reg_18_/Q, g_rf_flops_10__rf_reg_q_reg_17_/Q, g_rf_flops_10__rf_reg_q_reg_16_/Q, g_rf_flops_10__rf_reg_q_reg_15_/Q, g_rf_flops_10__rf_reg_q_reg_14_/Q, g_rf_flops_10__rf_reg_q_reg_13_/Q, g_rf_flops_10__rf_reg_q_reg_12_/Q, g_rf_flops_10__rf_reg_q_reg_11_/Q, g_rf_flops_10__rf_reg_q_reg_10_/Q, g_rf_flops_10__rf_reg_q_reg_9_/Q, g_rf_flops_10__rf_reg_q_reg_8_/Q, g_rf_flops_10__rf_reg_q_reg_7_/Q, g_rf_flops_10__rf_reg_q_reg_6_/Q, g_rf_flops_10__rf_reg_q_reg_5_/Q, g_rf_flops_10__rf_reg_q_reg_4_/Q, g_rf_flops_10__rf_reg_q_reg_3_/Q, g_rf_flops_10__rf_reg_q_reg_2_/Q, g_rf_flops_10__rf_reg_q_reg_1_/Q, g_rf_flops_10__rf_reg_q_reg_0_/Q}} reg10
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_11__rf_reg_q_reg_31_/Q, g_rf_flops_11__rf_reg_q_reg_30_/Q, g_rf_flops_11__rf_reg_q_reg_29_/Q, g_rf_flops_11__rf_reg_q_reg_28_/Q, g_rf_flops_11__rf_reg_q_reg_27_/Q, g_rf_flops_11__rf_reg_q_reg_26_/Q, g_rf_flops_11__rf_reg_q_reg_25_/Q, g_rf_flops_11__rf_reg_q_reg_24_/Q, g_rf_flops_11__rf_reg_q_reg_23_/Q, g_rf_flops_11__rf_reg_q_reg_22_/Q, g_rf_flops_11__rf_reg_q_reg_21_/Q, g_rf_flops_11__rf_reg_q_reg_20_/Q, g_rf_flops_11__rf_reg_q_reg_19_/Q, g_rf_flops_11__rf_reg_q_reg_18_/Q, g_rf_flops_11__rf_reg_q_reg_17_/Q, g_rf_flops_11__rf_reg_q_reg_16_/Q, g_rf_flops_11__rf_reg_q_reg_15_/Q, g_rf_flops_11__rf_reg_q_reg_14_/Q, g_rf_flops_11__rf_reg_q_reg_13_/Q, g_rf_flops_11__rf_reg_q_reg_12_/Q, g_rf_flops_11__rf_reg_q_reg_11_/Q, g_rf_flops_11__rf_reg_q_reg_10_/Q, g_rf_flops_11__rf_reg_q_reg_9_/Q, g_rf_flops_11__rf_reg_q_reg_8_/Q, g_rf_flops_11__rf_reg_q_reg_7_/Q, g_rf_flops_11__rf_reg_q_reg_6_/Q, g_rf_flops_11__rf_reg_q_reg_5_/Q, g_rf_flops_11__rf_reg_q_reg_4_/Q, g_rf_flops_11__rf_reg_q_reg_3_/Q, g_rf_flops_11__rf_reg_q_reg_2_/Q, g_rf_flops_11__rf_reg_q_reg_1_/Q, g_rf_flops_11__rf_reg_q_reg_0_/Q}} reg11
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_12__rf_reg_q_reg_31_/Q, g_rf_flops_12__rf_reg_q_reg_30_/Q, g_rf_flops_12__rf_reg_q_reg_29_/Q, g_rf_flops_12__rf_reg_q_reg_28_/Q, g_rf_flops_12__rf_reg_q_reg_27_/Q, g_rf_flops_12__rf_reg_q_reg_26_/Q, g_rf_flops_12__rf_reg_q_reg_25_/Q, g_rf_flops_12__rf_reg_q_reg_24_/Q, g_rf_flops_12__rf_reg_q_reg_23_/Q, g_rf_flops_12__rf_reg_q_reg_22_/Q, g_rf_flops_12__rf_reg_q_reg_21_/Q, g_rf_flops_12__rf_reg_q_reg_20_/Q, g_rf_flops_12__rf_reg_q_reg_19_/Q, g_rf_flops_12__rf_reg_q_reg_18_/Q, g_rf_flops_12__rf_reg_q_reg_17_/Q, g_rf_flops_12__rf_reg_q_reg_16_/Q, g_rf_flops_12__rf_reg_q_reg_15_/Q, g_rf_flops_12__rf_reg_q_reg_14_/Q, g_rf_flops_12__rf_reg_q_reg_13_/Q, g_rf_flops_12__rf_reg_q_reg_12_/Q, g_rf_flops_12__rf_reg_q_reg_11_/Q, g_rf_flops_12__rf_reg_q_reg_10_/Q, g_rf_flops_12__rf_reg_q_reg_9_/Q, g_rf_flops_12__rf_reg_q_reg_8_/Q, g_rf_flops_12__rf_reg_q_reg_7_/Q, g_rf_flops_12__rf_reg_q_reg_6_/Q, g_rf_flops_12__rf_reg_q_reg_5_/Q, g_rf_flops_12__rf_reg_q_reg_4_/Q, g_rf_flops_12__rf_reg_q_reg_3_/Q, g_rf_flops_12__rf_reg_q_reg_2_/Q, g_rf_flops_12__rf_reg_q_reg_1_/Q, g_rf_flops_12__rf_reg_q_reg_0_/Q}} reg12
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_13__rf_reg_q_reg_31_/Q, g_rf_flops_13__rf_reg_q_reg_30_/Q, g_rf_flops_13__rf_reg_q_reg_29_/Q, g_rf_flops_13__rf_reg_q_reg_28_/Q, g_rf_flops_13__rf_reg_q_reg_27_/Q, g_rf_flops_13__rf_reg_q_reg_26_/Q, g_rf_flops_13__rf_reg_q_reg_25_/Q, g_rf_flops_13__rf_reg_q_reg_24_/Q, g_rf_flops_13__rf_reg_q_reg_23_/Q, g_rf_flops_13__rf_reg_q_reg_22_/Q, g_rf_flops_13__rf_reg_q_reg_21_/Q, g_rf_flops_13__rf_reg_q_reg_20_/Q, g_rf_flops_13__rf_reg_q_reg_19_/Q, g_rf_flops_13__rf_reg_q_reg_18_/Q, g_rf_flops_13__rf_reg_q_reg_17_/Q, g_rf_flops_13__rf_reg_q_reg_16_/Q, g_rf_flops_13__rf_reg_q_reg_15_/Q, g_rf_flops_13__rf_reg_q_reg_14_/Q, g_rf_flops_13__rf_reg_q_reg_13_/Q, g_rf_flops_13__rf_reg_q_reg_12_/Q, g_rf_flops_13__rf_reg_q_reg_11_/Q, g_rf_flops_13__rf_reg_q_reg_10_/Q, g_rf_flops_13__rf_reg_q_reg_9_/Q, g_rf_flops_13__rf_reg_q_reg_8_/Q, g_rf_flops_13__rf_reg_q_reg_7_/Q, g_rf_flops_13__rf_reg_q_reg_6_/Q, g_rf_flops_13__rf_reg_q_reg_5_/Q, g_rf_flops_13__rf_reg_q_reg_4_/Q, g_rf_flops_13__rf_reg_q_reg_3_/Q, g_rf_flops_13__rf_reg_q_reg_2_/Q, g_rf_flops_13__rf_reg_q_reg_1_/Q, g_rf_flops_13__rf_reg_q_reg_0_/Q}} reg13
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_14__rf_reg_q_reg_31_/Q, g_rf_flops_14__rf_reg_q_reg_30_/Q, g_rf_flops_14__rf_reg_q_reg_29_/Q, g_rf_flops_14__rf_reg_q_reg_28_/Q, g_rf_flops_14__rf_reg_q_reg_27_/Q, g_rf_flops_14__rf_reg_q_reg_26_/Q, g_rf_flops_14__rf_reg_q_reg_25_/Q, g_rf_flops_14__rf_reg_q_reg_24_/Q, g_rf_flops_14__rf_reg_q_reg_23_/Q, g_rf_flops_14__rf_reg_q_reg_22_/Q, g_rf_flops_14__rf_reg_q_reg_21_/Q, g_rf_flops_14__rf_reg_q_reg_20_/Q, g_rf_flops_14__rf_reg_q_reg_19_/Q, g_rf_flops_14__rf_reg_q_reg_18_/Q, g_rf_flops_14__rf_reg_q_reg_17_/Q, g_rf_flops_14__rf_reg_q_reg_16_/Q, g_rf_flops_14__rf_reg_q_reg_15_/Q, g_rf_flops_14__rf_reg_q_reg_14_/Q, g_rf_flops_14__rf_reg_q_reg_13_/Q, g_rf_flops_14__rf_reg_q_reg_12_/Q, g_rf_flops_14__rf_reg_q_reg_11_/Q, g_rf_flops_14__rf_reg_q_reg_10_/Q, g_rf_flops_14__rf_reg_q_reg_9_/Q, g_rf_flops_14__rf_reg_q_reg_8_/Q, g_rf_flops_14__rf_reg_q_reg_7_/Q, g_rf_flops_14__rf_reg_q_reg_6_/Q, g_rf_flops_14__rf_reg_q_reg_5_/Q, g_rf_flops_14__rf_reg_q_reg_4_/Q, g_rf_flops_14__rf_reg_q_reg_3_/Q, g_rf_flops_14__rf_reg_q_reg_2_/Q, g_rf_flops_14__rf_reg_q_reg_1_/Q, g_rf_flops_14__rf_reg_q_reg_0_/Q}} reg14
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_15__rf_reg_q_reg_31_/Q, g_rf_flops_15__rf_reg_q_reg_30_/Q, g_rf_flops_15__rf_reg_q_reg_29_/Q, g_rf_flops_15__rf_reg_q_reg_28_/Q, g_rf_flops_15__rf_reg_q_reg_27_/Q, g_rf_flops_15__rf_reg_q_reg_26_/Q, g_rf_flops_15__rf_reg_q_reg_25_/Q, g_rf_flops_15__rf_reg_q_reg_24_/Q, g_rf_flops_15__rf_reg_q_reg_23_/Q, g_rf_flops_15__rf_reg_q_reg_22_/Q, g_rf_flops_15__rf_reg_q_reg_21_/Q, g_rf_flops_15__rf_reg_q_reg_20_/Q, g_rf_flops_15__rf_reg_q_reg_19_/Q, g_rf_flops_15__rf_reg_q_reg_18_/Q, g_rf_flops_15__rf_reg_q_reg_17_/Q, g_rf_flops_15__rf_reg_q_reg_16_/Q, g_rf_flops_15__rf_reg_q_reg_15_/Q, g_rf_flops_15__rf_reg_q_reg_14_/Q, g_rf_flops_15__rf_reg_q_reg_13_/Q, g_rf_flops_15__rf_reg_q_reg_12_/Q, g_rf_flops_15__rf_reg_q_reg_11_/Q, g_rf_flops_15__rf_reg_q_reg_10_/Q, g_rf_flops_15__rf_reg_q_reg_9_/Q, g_rf_flops_15__rf_reg_q_reg_8_/Q, g_rf_flops_15__rf_reg_q_reg_7_/Q, g_rf_flops_15__rf_reg_q_reg_6_/Q, g_rf_flops_15__rf_reg_q_reg_5_/Q, g_rf_flops_15__rf_reg_q_reg_4_/Q, g_rf_flops_15__rf_reg_q_reg_3_/Q, g_rf_flops_15__rf_reg_q_reg_2_/Q, g_rf_flops_15__rf_reg_q_reg_1_/Q, g_rf_flops_15__rf_reg_q_reg_0_/Q}} reg15
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_16__rf_reg_q_reg_31_/Q, g_rf_flops_16__rf_reg_q_reg_30_/Q, g_rf_flops_16__rf_reg_q_reg_29_/Q, g_rf_flops_16__rf_reg_q_reg_28_/Q, g_rf_flops_16__rf_reg_q_reg_27_/Q, g_rf_flops_16__rf_reg_q_reg_26_/Q, g_rf_flops_16__rf_reg_q_reg_25_/Q, g_rf_flops_16__rf_reg_q_reg_24_/Q, g_rf_flops_16__rf_reg_q_reg_23_/Q, g_rf_flops_16__rf_reg_q_reg_22_/Q, g_rf_flops_16__rf_reg_q_reg_21_/Q, g_rf_flops_16__rf_reg_q_reg_20_/Q, g_rf_flops_16__rf_reg_q_reg_19_/Q, g_rf_flops_16__rf_reg_q_reg_18_/Q, g_rf_flops_16__rf_reg_q_reg_17_/Q, g_rf_flops_16__rf_reg_q_reg_16_/Q, g_rf_flops_16__rf_reg_q_reg_15_/Q, g_rf_flops_16__rf_reg_q_reg_14_/Q, g_rf_flops_16__rf_reg_q_reg_13_/Q, g_rf_flops_16__rf_reg_q_reg_12_/Q, g_rf_flops_16__rf_reg_q_reg_11_/Q, g_rf_flops_16__rf_reg_q_reg_10_/Q, g_rf_flops_16__rf_reg_q_reg_9_/Q, g_rf_flops_16__rf_reg_q_reg_8_/Q, g_rf_flops_16__rf_reg_q_reg_7_/Q, g_rf_flops_16__rf_reg_q_reg_6_/Q, g_rf_flops_16__rf_reg_q_reg_5_/Q, g_rf_flops_16__rf_reg_q_reg_4_/Q, g_rf_flops_16__rf_reg_q_reg_3_/Q, g_rf_flops_16__rf_reg_q_reg_2_/Q, g_rf_flops_16__rf_reg_q_reg_1_/Q, g_rf_flops_16__rf_reg_q_reg_0_/Q}} reg16
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_17__rf_reg_q_reg_31_/Q, g_rf_flops_17__rf_reg_q_reg_30_/Q, g_rf_flops_17__rf_reg_q_reg_29_/Q, g_rf_flops_17__rf_reg_q_reg_28_/Q, g_rf_flops_17__rf_reg_q_reg_27_/Q, g_rf_flops_17__rf_reg_q_reg_26_/Q, g_rf_flops_17__rf_reg_q_reg_25_/Q, g_rf_flops_17__rf_reg_q_reg_24_/Q, g_rf_flops_17__rf_reg_q_reg_23_/Q, g_rf_flops_17__rf_reg_q_reg_22_/Q, g_rf_flops_17__rf_reg_q_reg_21_/Q, g_rf_flops_17__rf_reg_q_reg_20_/Q, g_rf_flops_17__rf_reg_q_reg_19_/Q, g_rf_flops_17__rf_reg_q_reg_18_/Q, g_rf_flops_17__rf_reg_q_reg_17_/Q, g_rf_flops_17__rf_reg_q_reg_16_/Q, g_rf_flops_17__rf_reg_q_reg_15_/Q, g_rf_flops_17__rf_reg_q_reg_14_/Q, g_rf_flops_17__rf_reg_q_reg_13_/Q, g_rf_flops_17__rf_reg_q_reg_12_/Q, g_rf_flops_17__rf_reg_q_reg_11_/Q, g_rf_flops_17__rf_reg_q_reg_10_/Q, g_rf_flops_17__rf_reg_q_reg_9_/Q, g_rf_flops_17__rf_reg_q_reg_8_/Q, g_rf_flops_17__rf_reg_q_reg_7_/Q, g_rf_flops_17__rf_reg_q_reg_6_/Q, g_rf_flops_17__rf_reg_q_reg_5_/Q, g_rf_flops_17__rf_reg_q_reg_4_/Q, g_rf_flops_17__rf_reg_q_reg_3_/Q, g_rf_flops_17__rf_reg_q_reg_2_/Q, g_rf_flops_17__rf_reg_q_reg_1_/Q, g_rf_flops_17__rf_reg_q_reg_0_/Q}} reg17
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_18__rf_reg_q_reg_31_/Q, g_rf_flops_18__rf_reg_q_reg_30_/Q, g_rf_flops_18__rf_reg_q_reg_29_/Q, g_rf_flops_18__rf_reg_q_reg_28_/Q, g_rf_flops_18__rf_reg_q_reg_27_/Q, g_rf_flops_18__rf_reg_q_reg_26_/Q, g_rf_flops_18__rf_reg_q_reg_25_/Q, g_rf_flops_18__rf_reg_q_reg_24_/Q, g_rf_flops_18__rf_reg_q_reg_23_/Q, g_rf_flops_18__rf_reg_q_reg_22_/Q, g_rf_flops_18__rf_reg_q_reg_21_/Q, g_rf_flops_18__rf_reg_q_reg_20_/Q, g_rf_flops_18__rf_reg_q_reg_19_/Q, g_rf_flops_18__rf_reg_q_reg_18_/Q, g_rf_flops_18__rf_reg_q_reg_17_/Q, g_rf_flops_18__rf_reg_q_reg_16_/Q, g_rf_flops_18__rf_reg_q_reg_15_/Q, g_rf_flops_18__rf_reg_q_reg_14_/Q, g_rf_flops_18__rf_reg_q_reg_13_/Q, g_rf_flops_18__rf_reg_q_reg_12_/Q, g_rf_flops_18__rf_reg_q_reg_11_/Q, g_rf_flops_18__rf_reg_q_reg_10_/Q, g_rf_flops_18__rf_reg_q_reg_9_/Q, g_rf_flops_18__rf_reg_q_reg_8_/Q, g_rf_flops_18__rf_reg_q_reg_7_/Q, g_rf_flops_18__rf_reg_q_reg_6_/Q, g_rf_flops_18__rf_reg_q_reg_5_/Q, g_rf_flops_18__rf_reg_q_reg_4_/Q, g_rf_flops_18__rf_reg_q_reg_3_/Q, g_rf_flops_18__rf_reg_q_reg_2_/Q, g_rf_flops_18__rf_reg_q_reg_1_/Q, g_rf_flops_18__rf_reg_q_reg_0_/Q}} reg18
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_19__rf_reg_q_reg_31_/Q, g_rf_flops_19__rf_reg_q_reg_30_/Q, g_rf_flops_19__rf_reg_q_reg_29_/Q, g_rf_flops_19__rf_reg_q_reg_28_/Q, g_rf_flops_19__rf_reg_q_reg_27_/Q, g_rf_flops_19__rf_reg_q_reg_26_/Q, g_rf_flops_19__rf_reg_q_reg_25_/Q, g_rf_flops_19__rf_reg_q_reg_24_/Q, g_rf_flops_19__rf_reg_q_reg_23_/Q, g_rf_flops_19__rf_reg_q_reg_22_/Q, g_rf_flops_19__rf_reg_q_reg_21_/Q, g_rf_flops_19__rf_reg_q_reg_20_/Q, g_rf_flops_19__rf_reg_q_reg_19_/Q, g_rf_flops_19__rf_reg_q_reg_18_/Q, g_rf_flops_19__rf_reg_q_reg_17_/Q, g_rf_flops_19__rf_reg_q_reg_16_/Q, g_rf_flops_19__rf_reg_q_reg_15_/Q, g_rf_flops_19__rf_reg_q_reg_14_/Q, g_rf_flops_19__rf_reg_q_reg_13_/Q, g_rf_flops_19__rf_reg_q_reg_12_/Q, g_rf_flops_19__rf_reg_q_reg_11_/Q, g_rf_flops_19__rf_reg_q_reg_10_/Q, g_rf_flops_19__rf_reg_q_reg_9_/Q, g_rf_flops_19__rf_reg_q_reg_8_/Q, g_rf_flops_19__rf_reg_q_reg_7_/Q, g_rf_flops_19__rf_reg_q_reg_6_/Q, g_rf_flops_19__rf_reg_q_reg_5_/Q, g_rf_flops_19__rf_reg_q_reg_4_/Q, g_rf_flops_19__rf_reg_q_reg_3_/Q, g_rf_flops_19__rf_reg_q_reg_2_/Q, g_rf_flops_19__rf_reg_q_reg_1_/Q, g_rf_flops_19__rf_reg_q_reg_0_/Q}} reg19
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_20__rf_reg_q_reg_31_/Q, g_rf_flops_20__rf_reg_q_reg_30_/Q, g_rf_flops_20__rf_reg_q_reg_29_/Q, g_rf_flops_20__rf_reg_q_reg_28_/Q, g_rf_flops_20__rf_reg_q_reg_27_/Q, g_rf_flops_20__rf_reg_q_reg_26_/Q, g_rf_flops_20__rf_reg_q_reg_25_/Q, g_rf_flops_20__rf_reg_q_reg_24_/Q, g_rf_flops_20__rf_reg_q_reg_23_/Q, g_rf_flops_20__rf_reg_q_reg_22_/Q, g_rf_flops_20__rf_reg_q_reg_21_/Q, g_rf_flops_20__rf_reg_q_reg_20_/Q, g_rf_flops_20__rf_reg_q_reg_19_/Q, g_rf_flops_20__rf_reg_q_reg_18_/Q, g_rf_flops_20__rf_reg_q_reg_17_/Q, g_rf_flops_20__rf_reg_q_reg_16_/Q, g_rf_flops_20__rf_reg_q_reg_15_/Q, g_rf_flops_20__rf_reg_q_reg_14_/Q, g_rf_flops_20__rf_reg_q_reg_13_/Q, g_rf_flops_20__rf_reg_q_reg_12_/Q, g_rf_flops_20__rf_reg_q_reg_11_/Q, g_rf_flops_20__rf_reg_q_reg_10_/Q, g_rf_flops_20__rf_reg_q_reg_9_/Q, g_rf_flops_20__rf_reg_q_reg_8_/Q, g_rf_flops_20__rf_reg_q_reg_7_/Q, g_rf_flops_20__rf_reg_q_reg_6_/Q, g_rf_flops_20__rf_reg_q_reg_5_/Q, g_rf_flops_20__rf_reg_q_reg_4_/Q, g_rf_flops_20__rf_reg_q_reg_3_/Q, g_rf_flops_20__rf_reg_q_reg_2_/Q, g_rf_flops_20__rf_reg_q_reg_1_/Q, g_rf_flops_20__rf_reg_q_reg_0_/Q}} reg20
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_21__rf_reg_q_reg_31_/Q, g_rf_flops_21__rf_reg_q_reg_30_/Q, g_rf_flops_21__rf_reg_q_reg_29_/Q, g_rf_flops_21__rf_reg_q_reg_28_/Q, g_rf_flops_21__rf_reg_q_reg_27_/Q, g_rf_flops_21__rf_reg_q_reg_26_/Q, g_rf_flops_21__rf_reg_q_reg_25_/Q, g_rf_flops_21__rf_reg_q_reg_24_/Q, g_rf_flops_21__rf_reg_q_reg_23_/Q, g_rf_flops_21__rf_reg_q_reg_22_/Q, g_rf_flops_21__rf_reg_q_reg_21_/Q, g_rf_flops_21__rf_reg_q_reg_20_/Q, g_rf_flops_21__rf_reg_q_reg_19_/Q, g_rf_flops_21__rf_reg_q_reg_18_/Q, g_rf_flops_21__rf_reg_q_reg_17_/Q, g_rf_flops_21__rf_reg_q_reg_16_/Q, g_rf_flops_21__rf_reg_q_reg_15_/Q, g_rf_flops_21__rf_reg_q_reg_14_/Q, g_rf_flops_21__rf_reg_q_reg_13_/Q, g_rf_flops_21__rf_reg_q_reg_12_/Q, g_rf_flops_21__rf_reg_q_reg_11_/Q, g_rf_flops_21__rf_reg_q_reg_10_/Q, g_rf_flops_21__rf_reg_q_reg_9_/Q, g_rf_flops_21__rf_reg_q_reg_8_/Q, g_rf_flops_21__rf_reg_q_reg_7_/Q, g_rf_flops_21__rf_reg_q_reg_6_/Q, g_rf_flops_21__rf_reg_q_reg_5_/Q, g_rf_flops_21__rf_reg_q_reg_4_/Q, g_rf_flops_21__rf_reg_q_reg_3_/Q, g_rf_flops_21__rf_reg_q_reg_2_/Q, g_rf_flops_21__rf_reg_q_reg_1_/Q, g_rf_flops_21__rf_reg_q_reg_0_/Q}} reg21
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_22__rf_reg_q_reg_31_/Q, g_rf_flops_22__rf_reg_q_reg_30_/Q, g_rf_flops_22__rf_reg_q_reg_29_/Q, g_rf_flops_22__rf_reg_q_reg_28_/Q, g_rf_flops_22__rf_reg_q_reg_27_/Q, g_rf_flops_22__rf_reg_q_reg_26_/Q, g_rf_flops_22__rf_reg_q_reg_25_/Q, g_rf_flops_22__rf_reg_q_reg_24_/Q, g_rf_flops_22__rf_reg_q_reg_23_/Q, g_rf_flops_22__rf_reg_q_reg_22_/Q, g_rf_flops_22__rf_reg_q_reg_21_/Q, g_rf_flops_22__rf_reg_q_reg_20_/Q, g_rf_flops_22__rf_reg_q_reg_19_/Q, g_rf_flops_22__rf_reg_q_reg_18_/Q, g_rf_flops_22__rf_reg_q_reg_17_/Q, g_rf_flops_22__rf_reg_q_reg_16_/Q, g_rf_flops_22__rf_reg_q_reg_15_/Q, g_rf_flops_22__rf_reg_q_reg_14_/Q, g_rf_flops_22__rf_reg_q_reg_13_/Q, g_rf_flops_22__rf_reg_q_reg_12_/Q, g_rf_flops_22__rf_reg_q_reg_11_/Q, g_rf_flops_22__rf_reg_q_reg_10_/Q, g_rf_flops_22__rf_reg_q_reg_9_/Q, g_rf_flops_22__rf_reg_q_reg_8_/Q, g_rf_flops_22__rf_reg_q_reg_7_/Q, g_rf_flops_22__rf_reg_q_reg_6_/Q, g_rf_flops_22__rf_reg_q_reg_5_/Q, g_rf_flops_22__rf_reg_q_reg_4_/Q, g_rf_flops_22__rf_reg_q_reg_3_/Q, g_rf_flops_22__rf_reg_q_reg_2_/Q, g_rf_flops_22__rf_reg_q_reg_1_/Q, g_rf_flops_22__rf_reg_q_reg_0_/Q}} reg22
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_23__rf_reg_q_reg_31_/Q, g_rf_flops_23__rf_reg_q_reg_30_/Q, g_rf_flops_23__rf_reg_q_reg_29_/Q, g_rf_flops_23__rf_reg_q_reg_28_/Q, g_rf_flops_23__rf_reg_q_reg_27_/Q, g_rf_flops_23__rf_reg_q_reg_26_/Q, g_rf_flops_23__rf_reg_q_reg_25_/Q, g_rf_flops_23__rf_reg_q_reg_24_/Q, g_rf_flops_23__rf_reg_q_reg_23_/Q, g_rf_flops_23__rf_reg_q_reg_22_/Q, g_rf_flops_23__rf_reg_q_reg_21_/Q, g_rf_flops_23__rf_reg_q_reg_20_/Q, g_rf_flops_23__rf_reg_q_reg_19_/Q, g_rf_flops_23__rf_reg_q_reg_18_/Q, g_rf_flops_23__rf_reg_q_reg_17_/Q, g_rf_flops_23__rf_reg_q_reg_16_/Q, g_rf_flops_23__rf_reg_q_reg_15_/Q, g_rf_flops_23__rf_reg_q_reg_14_/Q, g_rf_flops_23__rf_reg_q_reg_13_/Q, g_rf_flops_23__rf_reg_q_reg_12_/Q, g_rf_flops_23__rf_reg_q_reg_11_/Q, g_rf_flops_23__rf_reg_q_reg_10_/Q, g_rf_flops_23__rf_reg_q_reg_9_/Q, g_rf_flops_23__rf_reg_q_reg_8_/Q, g_rf_flops_23__rf_reg_q_reg_7_/Q, g_rf_flops_23__rf_reg_q_reg_6_/Q, g_rf_flops_23__rf_reg_q_reg_5_/Q, g_rf_flops_23__rf_reg_q_reg_4_/Q, g_rf_flops_23__rf_reg_q_reg_3_/Q, g_rf_flops_23__rf_reg_q_reg_2_/Q, g_rf_flops_23__rf_reg_q_reg_1_/Q, g_rf_flops_23__rf_reg_q_reg_0_/Q}} reg23
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_24__rf_reg_q_reg_31_/Q, g_rf_flops_24__rf_reg_q_reg_30_/Q, g_rf_flops_24__rf_reg_q_reg_29_/Q, g_rf_flops_24__rf_reg_q_reg_28_/Q, g_rf_flops_24__rf_reg_q_reg_27_/Q, g_rf_flops_24__rf_reg_q_reg_26_/Q, g_rf_flops_24__rf_reg_q_reg_25_/Q, g_rf_flops_24__rf_reg_q_reg_24_/Q, g_rf_flops_24__rf_reg_q_reg_23_/Q, g_rf_flops_24__rf_reg_q_reg_22_/Q, g_rf_flops_24__rf_reg_q_reg_21_/Q, g_rf_flops_24__rf_reg_q_reg_20_/Q, g_rf_flops_24__rf_reg_q_reg_19_/Q, g_rf_flops_24__rf_reg_q_reg_18_/Q, g_rf_flops_24__rf_reg_q_reg_17_/Q, g_rf_flops_24__rf_reg_q_reg_16_/Q, g_rf_flops_24__rf_reg_q_reg_15_/Q, g_rf_flops_24__rf_reg_q_reg_14_/Q, g_rf_flops_24__rf_reg_q_reg_13_/Q, g_rf_flops_24__rf_reg_q_reg_12_/Q, g_rf_flops_24__rf_reg_q_reg_11_/Q, g_rf_flops_24__rf_reg_q_reg_10_/Q, g_rf_flops_24__rf_reg_q_reg_9_/Q, g_rf_flops_24__rf_reg_q_reg_8_/Q, g_rf_flops_24__rf_reg_q_reg_7_/Q, g_rf_flops_24__rf_reg_q_reg_6_/Q, g_rf_flops_24__rf_reg_q_reg_5_/Q, g_rf_flops_24__rf_reg_q_reg_4_/Q, g_rf_flops_24__rf_reg_q_reg_3_/Q, g_rf_flops_24__rf_reg_q_reg_2_/Q, g_rf_flops_24__rf_reg_q_reg_1_/Q, g_rf_flops_24__rf_reg_q_reg_0_/Q}} reg24
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_25__rf_reg_q_reg_31_/Q, g_rf_flops_25__rf_reg_q_reg_30_/Q, g_rf_flops_25__rf_reg_q_reg_29_/Q, g_rf_flops_25__rf_reg_q_reg_28_/Q, g_rf_flops_25__rf_reg_q_reg_27_/Q, g_rf_flops_25__rf_reg_q_reg_26_/Q, g_rf_flops_25__rf_reg_q_reg_25_/Q, g_rf_flops_25__rf_reg_q_reg_24_/Q, g_rf_flops_25__rf_reg_q_reg_23_/Q, g_rf_flops_25__rf_reg_q_reg_22_/Q, g_rf_flops_25__rf_reg_q_reg_21_/Q, g_rf_flops_25__rf_reg_q_reg_20_/Q, g_rf_flops_25__rf_reg_q_reg_19_/Q, g_rf_flops_25__rf_reg_q_reg_18_/Q, g_rf_flops_25__rf_reg_q_reg_17_/Q, g_rf_flops_25__rf_reg_q_reg_16_/Q, g_rf_flops_25__rf_reg_q_reg_15_/Q, g_rf_flops_25__rf_reg_q_reg_14_/Q, g_rf_flops_25__rf_reg_q_reg_13_/Q, g_rf_flops_25__rf_reg_q_reg_12_/Q, g_rf_flops_25__rf_reg_q_reg_11_/Q, g_rf_flops_25__rf_reg_q_reg_10_/Q, g_rf_flops_25__rf_reg_q_reg_9_/Q, g_rf_flops_25__rf_reg_q_reg_8_/Q, g_rf_flops_25__rf_reg_q_reg_7_/Q, g_rf_flops_25__rf_reg_q_reg_6_/Q, g_rf_flops_25__rf_reg_q_reg_5_/Q, g_rf_flops_25__rf_reg_q_reg_4_/Q, g_rf_flops_25__rf_reg_q_reg_3_/Q, g_rf_flops_25__rf_reg_q_reg_2_/Q, g_rf_flops_25__rf_reg_q_reg_1_/Q, g_rf_flops_25__rf_reg_q_reg_0_/Q}} reg25
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_26__rf_reg_q_reg_31_/Q, g_rf_flops_26__rf_reg_q_reg_30_/Q, g_rf_flops_26__rf_reg_q_reg_29_/Q, g_rf_flops_26__rf_reg_q_reg_28_/Q, g_rf_flops_26__rf_reg_q_reg_27_/Q, g_rf_flops_26__rf_reg_q_reg_26_/Q, g_rf_flops_26__rf_reg_q_reg_25_/Q, g_rf_flops_26__rf_reg_q_reg_24_/Q, g_rf_flops_26__rf_reg_q_reg_23_/Q, g_rf_flops_26__rf_reg_q_reg_22_/Q, g_rf_flops_26__rf_reg_q_reg_21_/Q, g_rf_flops_26__rf_reg_q_reg_20_/Q, g_rf_flops_26__rf_reg_q_reg_19_/Q, g_rf_flops_26__rf_reg_q_reg_18_/Q, g_rf_flops_26__rf_reg_q_reg_17_/Q, g_rf_flops_26__rf_reg_q_reg_16_/Q, g_rf_flops_26__rf_reg_q_reg_15_/Q, g_rf_flops_26__rf_reg_q_reg_14_/Q, g_rf_flops_26__rf_reg_q_reg_13_/Q, g_rf_flops_26__rf_reg_q_reg_12_/Q, g_rf_flops_26__rf_reg_q_reg_11_/Q, g_rf_flops_26__rf_reg_q_reg_10_/Q, g_rf_flops_26__rf_reg_q_reg_9_/Q, g_rf_flops_26__rf_reg_q_reg_8_/Q, g_rf_flops_26__rf_reg_q_reg_7_/Q, g_rf_flops_26__rf_reg_q_reg_6_/Q, g_rf_flops_26__rf_reg_q_reg_5_/Q, g_rf_flops_26__rf_reg_q_reg_4_/Q, g_rf_flops_26__rf_reg_q_reg_3_/Q, g_rf_flops_26__rf_reg_q_reg_2_/Q, g_rf_flops_26__rf_reg_q_reg_1_/Q, g_rf_flops_26__rf_reg_q_reg_0_/Q}} reg26
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_27__rf_reg_q_reg_31_/Q, g_rf_flops_27__rf_reg_q_reg_30_/Q, g_rf_flops_27__rf_reg_q_reg_29_/Q, g_rf_flops_27__rf_reg_q_reg_28_/Q, g_rf_flops_27__rf_reg_q_reg_27_/Q, g_rf_flops_27__rf_reg_q_reg_26_/Q, g_rf_flops_27__rf_reg_q_reg_25_/Q, g_rf_flops_27__rf_reg_q_reg_24_/Q, g_rf_flops_27__rf_reg_q_reg_23_/Q, g_rf_flops_27__rf_reg_q_reg_22_/Q, g_rf_flops_27__rf_reg_q_reg_21_/Q, g_rf_flops_27__rf_reg_q_reg_20_/Q, g_rf_flops_27__rf_reg_q_reg_19_/Q, g_rf_flops_27__rf_reg_q_reg_18_/Q, g_rf_flops_27__rf_reg_q_reg_17_/Q, g_rf_flops_27__rf_reg_q_reg_16_/Q, g_rf_flops_27__rf_reg_q_reg_15_/Q, g_rf_flops_27__rf_reg_q_reg_14_/Q, g_rf_flops_27__rf_reg_q_reg_13_/Q, g_rf_flops_27__rf_reg_q_reg_12_/Q, g_rf_flops_27__rf_reg_q_reg_11_/Q, g_rf_flops_27__rf_reg_q_reg_10_/Q, g_rf_flops_27__rf_reg_q_reg_9_/Q, g_rf_flops_27__rf_reg_q_reg_8_/Q, g_rf_flops_27__rf_reg_q_reg_7_/Q, g_rf_flops_27__rf_reg_q_reg_6_/Q, g_rf_flops_27__rf_reg_q_reg_5_/Q, g_rf_flops_27__rf_reg_q_reg_4_/Q, g_rf_flops_27__rf_reg_q_reg_3_/Q, g_rf_flops_27__rf_reg_q_reg_2_/Q, g_rf_flops_27__rf_reg_q_reg_1_/Q, g_rf_flops_27__rf_reg_q_reg_0_/Q}} reg27
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_28__rf_reg_q_reg_31_/Q, g_rf_flops_28__rf_reg_q_reg_30_/Q, g_rf_flops_28__rf_reg_q_reg_29_/Q, g_rf_flops_28__rf_reg_q_reg_28_/Q, g_rf_flops_28__rf_reg_q_reg_27_/Q, g_rf_flops_28__rf_reg_q_reg_26_/Q, g_rf_flops_28__rf_reg_q_reg_25_/Q, g_rf_flops_28__rf_reg_q_reg_24_/Q, g_rf_flops_28__rf_reg_q_reg_23_/Q, g_rf_flops_28__rf_reg_q_reg_22_/Q, g_rf_flops_28__rf_reg_q_reg_21_/Q, g_rf_flops_28__rf_reg_q_reg_20_/Q, g_rf_flops_28__rf_reg_q_reg_19_/Q, g_rf_flops_28__rf_reg_q_reg_18_/Q, g_rf_flops_28__rf_reg_q_reg_17_/Q, g_rf_flops_28__rf_reg_q_reg_16_/Q, g_rf_flops_28__rf_reg_q_reg_15_/Q, g_rf_flops_28__rf_reg_q_reg_14_/Q, g_rf_flops_28__rf_reg_q_reg_13_/Q, g_rf_flops_28__rf_reg_q_reg_12_/Q, g_rf_flops_28__rf_reg_q_reg_11_/Q, g_rf_flops_28__rf_reg_q_reg_10_/Q, g_rf_flops_28__rf_reg_q_reg_9_/Q, g_rf_flops_28__rf_reg_q_reg_8_/Q, g_rf_flops_28__rf_reg_q_reg_7_/Q, g_rf_flops_28__rf_reg_q_reg_6_/Q, g_rf_flops_28__rf_reg_q_reg_5_/Q, g_rf_flops_28__rf_reg_q_reg_4_/Q, g_rf_flops_28__rf_reg_q_reg_3_/Q, g_rf_flops_28__rf_reg_q_reg_2_/Q, g_rf_flops_28__rf_reg_q_reg_1_/Q, g_rf_flops_28__rf_reg_q_reg_0_/Q}} reg28
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_29__rf_reg_q_reg_31_/Q, g_rf_flops_29__rf_reg_q_reg_30_/Q, g_rf_flops_29__rf_reg_q_reg_29_/Q, g_rf_flops_29__rf_reg_q_reg_28_/Q, g_rf_flops_29__rf_reg_q_reg_27_/Q, g_rf_flops_29__rf_reg_q_reg_26_/Q, g_rf_flops_29__rf_reg_q_reg_25_/Q, g_rf_flops_29__rf_reg_q_reg_24_/Q, g_rf_flops_29__rf_reg_q_reg_23_/Q, g_rf_flops_29__rf_reg_q_reg_22_/Q, g_rf_flops_29__rf_reg_q_reg_21_/Q, g_rf_flops_29__rf_reg_q_reg_20_/Q, g_rf_flops_29__rf_reg_q_reg_19_/Q, g_rf_flops_29__rf_reg_q_reg_18_/Q, g_rf_flops_29__rf_reg_q_reg_17_/Q, g_rf_flops_29__rf_reg_q_reg_16_/Q, g_rf_flops_29__rf_reg_q_reg_15_/Q, g_rf_flops_29__rf_reg_q_reg_14_/Q, g_rf_flops_29__rf_reg_q_reg_13_/Q, g_rf_flops_29__rf_reg_q_reg_12_/Q, g_rf_flops_29__rf_reg_q_reg_11_/Q, g_rf_flops_29__rf_reg_q_reg_10_/Q, g_rf_flops_29__rf_reg_q_reg_9_/Q, g_rf_flops_29__rf_reg_q_reg_8_/Q, g_rf_flops_29__rf_reg_q_reg_7_/Q, g_rf_flops_29__rf_reg_q_reg_6_/Q, g_rf_flops_29__rf_reg_q_reg_5_/Q, g_rf_flops_29__rf_reg_q_reg_4_/Q, g_rf_flops_29__rf_reg_q_reg_3_/Q, g_rf_flops_29__rf_reg_q_reg_2_/Q, g_rf_flops_29__rf_reg_q_reg_1_/Q, g_rf_flops_29__rf_reg_q_reg_0_/Q}} reg29
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_30__rf_reg_q_reg_31_/Q, g_rf_flops_30__rf_reg_q_reg_30_/Q, g_rf_flops_30__rf_reg_q_reg_29_/Q, g_rf_flops_30__rf_reg_q_reg_28_/Q, g_rf_flops_30__rf_reg_q_reg_27_/Q, g_rf_flops_30__rf_reg_q_reg_26_/Q, g_rf_flops_30__rf_reg_q_reg_25_/Q, g_rf_flops_30__rf_reg_q_reg_24_/Q, g_rf_flops_30__rf_reg_q_reg_23_/Q, g_rf_flops_30__rf_reg_q_reg_22_/Q, g_rf_flops_30__rf_reg_q_reg_21_/Q, g_rf_flops_30__rf_reg_q_reg_20_/Q, g_rf_flops_30__rf_reg_q_reg_19_/Q, g_rf_flops_30__rf_reg_q_reg_18_/Q, g_rf_flops_30__rf_reg_q_reg_17_/Q, g_rf_flops_30__rf_reg_q_reg_16_/Q, g_rf_flops_30__rf_reg_q_reg_15_/Q, g_rf_flops_30__rf_reg_q_reg_14_/Q, g_rf_flops_30__rf_reg_q_reg_13_/Q, g_rf_flops_30__rf_reg_q_reg_12_/Q, g_rf_flops_30__rf_reg_q_reg_11_/Q, g_rf_flops_30__rf_reg_q_reg_10_/Q, g_rf_flops_30__rf_reg_q_reg_9_/Q, g_rf_flops_30__rf_reg_q_reg_8_/Q, g_rf_flops_30__rf_reg_q_reg_7_/Q, g_rf_flops_30__rf_reg_q_reg_6_/Q, g_rf_flops_30__rf_reg_q_reg_5_/Q, g_rf_flops_30__rf_reg_q_reg_4_/Q, g_rf_flops_30__rf_reg_q_reg_3_/Q, g_rf_flops_30__rf_reg_q_reg_2_/Q, g_rf_flops_30__rf_reg_q_reg_1_/Q, g_rf_flops_30__rf_reg_q_reg_0_/Q}} reg30
quietly virtual signal -install tb_top/dut/gen_regfile_ff_register_file_i { (context tb_top/dut/gen_regfile_ff_register_file_i )&{g_rf_flops_31__rf_reg_q_reg_31_/Q, g_rf_flops_31__rf_reg_q_reg_30_/Q, g_rf_flops_31__rf_reg_q_reg_29_/Q, g_rf_flops_31__rf_reg_q_reg_28_/Q, g_rf_flops_31__rf_reg_q_reg_27_/Q, g_rf_flops_31__rf_reg_q_reg_26_/Q, g_rf_flops_31__rf_reg_q_reg_25_/Q, g_rf_flops_31__rf_reg_q_reg_24_/Q, g_rf_flops_31__rf_reg_q_reg_23_/Q, g_rf_flops_31__rf_reg_q_reg_22_/Q, g_rf_flops_31__rf_reg_q_reg_21_/Q, g_rf_flops_31__rf_reg_q_reg_20_/Q, g_rf_flops_31__rf_reg_q_reg_19_/Q, g_rf_flops_31__rf_reg_q_reg_18_/Q, g_rf_flops_31__rf_reg_q_reg_17_/Q, g_rf_flops_31__rf_reg_q_reg_16_/Q, g_rf_flops_31__rf_reg_q_reg_15_/Q, g_rf_flops_31__rf_reg_q_reg_14_/Q, g_rf_flops_31__rf_reg_q_reg_13_/Q, g_rf_flops_31__rf_reg_q_reg_12_/Q, g_rf_flops_31__rf_reg_q_reg_11_/Q, g_rf_flops_31__rf_reg_q_reg_10_/Q, g_rf_flops_31__rf_reg_q_reg_9_/Q, g_rf_flops_31__rf_reg_q_reg_8_/Q, g_rf_flops_31__rf_reg_q_reg_7_/Q, g_rf_flops_31__rf_reg_q_reg_6_/Q, g_rf_flops_31__rf_reg_q_reg_5_/Q, g_rf_flops_31__rf_reg_q_reg_4_/Q, g_rf_flops_31__rf_reg_q_reg_3_/Q, g_rf_flops_31__rf_reg_q_reg_2_/Q, g_rf_flops_31__rf_reg_q_reg_1_/Q, g_rf_flops_31__rf_reg_q_reg_0_/Q}} reg31

add wave -divider REGISTER\ FILE 

add wave -group REGISTER\ FILE -color cyan -label \[r1\]\ ra\ Return\ Address\ Reg tb_top/dut/gen_regfile_ff_register_file_i/reg1
add wave -group REGISTER\ FILE -color cyan -label \[r2\]\ sp\ Stack\ Pointer\ Reg  tb_top/dut/gen_regfile_ff_register_file_i/reg2
add wave -group REGISTER\ FILE -color cyan -label \[r3\]\ gp\ Global\ Pointer\ Reg tb_top/dut/gen_regfile_ff_register_file_i/reg3 
add wave -group REGISTER\ FILE -color cyan -label \[r4\]\ tp\ Thread\ Pointer\ Reg tb_top/dut/gen_regfile_ff_register_file_i/reg4 
add wave -group REGISTER\ FILE -group TEMP\ REGS -color cyan -label \[r5\]\ t0\ Temp\ Reg\ 0 tb_top/dut/gen_regfile_ff_register_file_i/reg5 
add wave -group REGISTER\ FILE -group TEMP\ REGS -color cyan -label \[r6\]\ t1\ Temp\ Reg\ 1 tb_top/dut/gen_regfile_ff_register_file_i/reg6 
add wave -group REGISTER\ FILE -group TEMP\ REGS -color cyan -label \[r7\]\ t2\ Temp\ Reg\ 2 tb_top/dut/gen_regfile_ff_register_file_i/reg7 
add wave -group REGISTER\ FILE -group SAVED\ REGS -color cyan -label \[r8\]\ s0\ Saved\ Reg\ 1 tb_top/dut/gen_regfile_ff_register_file_i/reg8 
add wave -group REGISTER\ FILE -group SAVED\ REGS -color cyan -label \[r9\]\ s1\ Saved\ Reg\ 2 tb_top/dut/gen_regfile_ff_register_file_i/reg9 
add wave -group REGISTER\ FILE -group ARG\ REGS -color cyan -label \[r10\]\ a0\ Arg\ Reg\ 0 tb_top/dut/gen_regfile_ff_register_file_i/reg10 
add wave -group REGISTER\ FILE -group ARG\ REGS -color cyan -label \[r11\]\ a1\ Arg\ Reg\ 1 tb_top/dut/gen_regfile_ff_register_file_i/reg11 
add wave -group REGISTER\ FILE -group ARG\ REGS -color cyan -label \[r12\]\ a2\ Arg\ Reg\ 2 tb_top/dut/gen_regfile_ff_register_file_i/reg12 
add wave -group REGISTER\ FILE -group ARG\ REGS -color cyan -label \[r13\]\ a3\ Arg\ Reg\ 3 tb_top/dut/gen_regfile_ff_register_file_i/reg13 
add wave -group REGISTER\ FILE -group ARG\ REGS -color cyan -label \[r14\]\ a4\ Arg\ Reg\ 4 tb_top/dut/gen_regfile_ff_register_file_i/reg14 
add wave -group REGISTER\ FILE -group ARG\ REGS -color cyan -label \[r15\]\ a5\ Arg\ Reg\ 5 tb_top/dut/gen_regfile_ff_register_file_i/reg15 
add wave -group REGISTER\ FILE -group ARG\ REGS -color cyan -label \[r16\]\ a6\ Arg\ Reg\ 6 tb_top/dut/gen_regfile_ff_register_file_i/reg16 
add wave -group REGISTER\ FILE -group ARG\ REGS -color cyan -label \[r17\]\ a7\ Arg\ Reg\ 7 tb_top/dut/gen_regfile_ff_register_file_i/reg17 
add wave -group REGISTER\ FILE -group SAVED\ REGS -color cyan -label \[r18\]\ s2\ Saved\ Reg\ 2  tb_top/dut/gen_regfile_ff_register_file_i/reg18
add wave -group REGISTER\ FILE -group SAVED\ REGS -color cyan -label \[r19\]\ s3\ Saved\ Reg\ 3 tb_top/dut/gen_regfile_ff_register_file_i/reg19
add wave -group REGISTER\ FILE -group SAVED\ REGS -color cyan -label \[r20\]\ s4\ Saved\ Reg\ 4 tb_top/dut/gen_regfile_ff_register_file_i/reg20
add wave -group REGISTER\ FILE -group SAVED\ REGS -color cyan -label \[r21\]\ s5\ Saved\ Reg\ 5 tb_top/dut/gen_regfile_ff_register_file_i/reg21
add wave -group REGISTER\ FILE -group SAVED\ REGS -color cyan -label \[r22\]\ s6\ Saved\ Reg\ 6 tb_top/dut/gen_regfile_ff_register_file_i/reg22
add wave -group REGISTER\ FILE -group SAVED\ REGS -color cyan -label \[r23\]\ s7\ Saved\ Reg\ 7 tb_top/dut/gen_regfile_ff_register_file_i/reg23
add wave -group REGISTER\ FILE -group SAVED\ REGS -color cyan -label \[r24\]\ s8\ Saved\ Reg\ 8 tb_top/dut/gen_regfile_ff_register_file_i/reg24
add wave -group REGISTER\ FILE -group SAVED\ REGS -color cyan -label \[r25\]\ s9\ Saved\ Reg\ 9 tb_top/dut/gen_regfile_ff_register_file_i/reg25
add wave -group REGISTER\ FILE -group SAVED\ REGS -color cyan -label \[r26\]\ s10\ Saved\ Reg\ 10  tb_top/dut/gen_regfile_ff_register_file_i/reg26
add wave -group REGISTER\ FILE -group SAVED\ REGS -color cyan -label \[r27\]\ s11\ Saved\ Reg\ 11 tb_top/dut/gen_regfile_ff_register_file_i/reg27
add wave -group REGISTER\ FILE -group TEMP\ REGS -color cyan -label \[r28\]\ t3\ Temp\ Reg\ 3 tb_top/dut/gen_regfile_ff_register_file_i/reg28
add wave -group REGISTER\ FILE -group TEMP\ REGS -color cyan -label \[r29\]\ t4\ Temp\ Reg\ 4 tb_top/dut/gen_regfile_ff_register_file_i/reg29
add wave -group REGISTER\ FILE -group TEMP\ REGS -color cyan -label \[r30\]\ t5\ Temp\ Reg\ 5 tb_top/dut/gen_regfile_ff_register_file_i/reg30
add wave -group REGISTER\ FILE -group TEMP\ REGS -color cyan -label \[r31\]\ t6\ Temp\ Reg\ 6 tb_top/dut/gen_regfile_ff_register_file_i/reg31

add wave -divider RAM
foreach sig $I_MEMORY {
    add wave -group RAM -group i_ram -label [file tail $sig] -color yellow $sig
}

foreach sig $D_MEMORY {
    add wave -group RAM -group d_ram -label [file tail $sig] -color orange $sig
}

###################### CORE #######################
add wave -divider IBEX\ CORE
   
    ###################### IF #######################

    foreach sig $IF {
        add wave -group IBEX -group IF -label [file tail $sig] -color green $sig 
    }

    foreach sig $IF_PREF {
        add wave -group IBEX -group IF -group PREFETCH\ BUFFER -label [file tail $sig] -color green $sig 
    }
    
    foreach sig $IF_CDEC {
        add wave -group IBEX -group IF -group COMPRESSED\ DECODER -label [file tail $sig] -color green $sig 
    }

    ###################### ID #######################

    foreach sig $ID {
        add wave -group IBEX -group ID -label [file tail $sig] -color green $sig 
    }

    foreach sig $ID_DEC {
        add wave -group IBEX -group ID -group DECODER -label [file tail $sig] -color green $sig 
    }

    foreach sig $ID_CONTR {
        add wave -group IBEX -group ID -group CONTROLLER -label [file tail $sig] -color green $sig 
    }

    foreach sig $ID_STALL {
        add wave -group IBEX -group ID -group STALLS -label [file tail $sig] -color green $sig 
    }

    ###################### EX #######################

    foreach sig $EX {
        add wave -group IBEX -group EX -label [file tail $sig] -color green $sig 
    }

    foreach sig $EX_ALU {
        add wave -group IBEX -group EX -group ALU -label [file tail $sig] -color green $sig 
    }

    ###################### LSU #######################

    foreach sig $LSU {
        add wave -group IBEX -group LSU -label [file tail $sig] -color green $sig 
    }

    ###################### WB #######################

    foreach sig $WB {
        add wave -group IBEX -group WB -label [file tail $sig] -color green $sig 

    }   

